### ISSUE TITLE
Sigmet Reader Todo List

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib#180]
The Sigmet IRIS Reader is in general capable of reading all types of product files:

* Ingest Data Files
* RAW product (polar data)
* cartesian products (MAX, TOPs etc)
* other products (FCAST, SLINE, WARN, WIND)

The overall class-structure is fixed, but this is what is yet to be done:

* [ ] thorough documentation
* [ ] decoding of data review (is all data converted correctly using the given sigmet_data_type)
* [ ] add necessary decoding functions
* [ ] mask nodata and area not scanned (or add array-masks)
* [ ] add necessary data structs (there are still some left)
* [ ] check class-properties (getters/setters)
* [x] possibly add class-structures for headers  PR #303 
* [ ] check for possible simplifications in functions
* [x] fix `DB_KDP` decoding (division by wavelenght) #195 
* [ ] research windows issue, where unusual high kdp values are extracted at some bins
* [x] decode iris DB_XHDR as numpy structured array #488 
* [x] add rainrate decoder to iris reader #428
* [x] make RAW files lazy loading and improve reading #520 
* [x] add xarray backend for RAW files #520 

See the [source code](https://github.com/wradlib/wradlib/blob/master/wradlib/io/iris.py).

**Comment by kmuehlbauer** [comment]
This still lacks sigmet test files of all products. If there is someone who can provide these data files to be made openly available, just contact wradlib maintainers.

**Comment by kmuehlbauer** [comment]
The development continues in xradar-package https://github.com/openradar/xradar for polar source data.

Cartesian data is handled here until decision if xradar will take care of cartesian data too.
