### ISSUE TITLE
master module rework

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib#224]
Update: `strip1.0.0` branch is switched to master now.

This is a list with changes to the different wradlib modules:

- adjust:    
    - [x]  add tests to `adjust` #246 
    - [x]  fix `_get_statfunc` #246 
    - [x]  remove `_get_neighbours` #246 
    - [x] remove commented `raw_at_obs` #246 
- atten:
    - [x]  add tests to `atten` #245 
    - [x] fix strings #245 
    - [x] fix issue (#240) #245  
    - [x] refactor naming, 
    - [x] remove/combine functions
- clutter: 
    - [x] add tests #248 
- comp: 
    - [x] add tests to `comp` #238 
    - [x] commented `extract_circle` KDTRee implementation #247 
- dp: 
    - [x] add tests to `dp` #241 
    - [x] rework `kdp_from_phidp` #241 
    - [x] remove unused functions (`contiguous_regions`) #241 
    - [x] move `medfilt_along_axis`, `gradient_along_axis`, 
`gradient_from_smoothed`
- fill:
    - [x] remove module #242 
- georef:
    - [x] add tests to georef
    - [x] remove duplicate functions from `misc`
    - [x] several minor fixes
    - [x] renamed `get_shape_coordinates` to `get_vector_coordinates`
    - [x] renamed `get_shape_points` to `get_vector_points`
    - [ ] usage of `georef.ogr_to_numpy` can be replaced by `georef.get_vector_points`)
- io:
    - [x] add tests to io #234 
- ipol: 
    - [x] add tests #244 
    - [x] rework Kriging  class structure - postponed (see issue #255) 
    - [x] add examples
- qual:
    - [x] add tests to `qual` #235 
    - [x] remove `beam_height_ft`-functions, replace usage with `georef.bin_altitude` #235 
- util: 
    - [x] remove apichange_kwarg, since we can do this more thorough with    `warnings.warn(FutureWarning...` #231 
    - [x] add tests to increase coverage #231 
- verify:
    - [x] add tests to `verify` #237 
    - [x] fix Exception and Warning #237 
    - [x] think about matplotlib --> removed ErrorMetrics.plot and report 
- vis: 
    - [x] add tests to `vis` #236 
    - [x] remove `NorthPolarAxis`, fix usage of `PolarTransform` in `create_cg` #236 
    - [x] remove `plot_tseries` #236 
- vpr:
    - [x] add tests #243 
    - [x] rework docstrings
- zonalstats:
    - [x] removed some unneeded code #232 
    - [x] added tests #232 
    - [x] rename `GridCellsToPoly` to `ZonalStatsPoly` #259 
    - [x] rename `GridPointsToPoly` to `ZonalStatsPoint` #259
    - [ ] usage of `georef.ogr_to_numpy` can be replaced by `georef.get_shape_points` (which will be renamed to `georef.get_vector_points`)
    - [x] removed sole usage of `georef.ogr_geocol_to_numpy` #232 
    - [x] removed sole usage of `georef.ogr_add_geometry` #232 
    - [x] removed sole usage of `georef.get_centroid` #232 
- zr : 
    - [x] add tests #239 
    - [x] remove z2rEnhanced_md #239  
    - [x] fix `z2rEnhanced` to use different algorithms #239 
   
- everywhere:
    - use constants
    - consolidate (r, phi, theta) nomenclature
    - tbc

**Comment by kmuehlbauer** [comment]
@heistermann I've addressed all modules with a first run adding tests and making (minor) changes. There are some open checkboxes above which need to be addressed as well. Or at least we need to think about how we should handle those cases.

This means also, that after handling the remaining issues, we can switch the `strip1.0.0`-branch to master.

**Comment by kmuehlbauer** [comment]
close as resolved for 1.0.0
