### ISSUE TITLE
Finalize Release 0.9.0

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib#83]
Steps to be done to finalize release 0.9.0:

- [x] Fix release notes (add changelog), see #84 
- [x] Find and fix inter-doc-link issues (docstrings, eg. links to generated-api-functions ), see #84 
- [x] review Tutorials and Examples doc-section (headings, toc etc) - > ongoing work
- [x] repair Note, Seealso, Warning in Notebooks (see [wradlib_workflow](https://github.com/wradlib/wradlib/blob/master/notebooks/basics/wradlib_workflow.ipynb) for guidance, but do not use github renderer for evaluation, it's broken in some way)  
- [x] fix #54 (Math in Docs)
- [x] tackle #45 (80% code coverage)
- [x] fix issue #86
- [x] add a tutorial section on how to use notebooks #91 
- [x] add a brief Python intro layout #92 
- [x] add CONTRIBUTING.md #99 
- [x] update release notes #97 
- please add other necessary steps here or in the comments below

**Comment by heistermann** [comment]
In the TOC of "Tutorials and Examples", some headers lack a whitespace inbetween words (example: http://wradlib.org/wradlib-docs/latest/notebooks.html > "Typical Workflow for Radar-Based RainfallEstimation"). I think these are all from section headers inside notebooks. I have no clue about the cause - the raw headers in the notebooks look fine to me. However, this should not be a showstopper for this release.

**Comment by kmuehlbauer** [comment]
> I have no clue about the cause - the raw headers in the notebooks look fine to me. However, this should not be a showstopper for this release.

Me neither. I'll have some checks to hopefully find the cause of this.

**Comment by heistermann** [comment]
@kmuehlbauer: Is there anything you would still need for this release? One check mark is still missing at `review Tutorials and Examples doc-section`, but I did not find anything serious, and I think it is an ongoing issue anyway.

**Comment by kmuehlbauer** [comment]
@heistermann I'd love to get out 0.9.0 asap. It is all very much done now, especially the addition to examples and tutorials. We only need to get all changes into the changeling (most is already in,  but the latest Bugfixes are missing there). So we can move forward and release 0.9.0.

**Comment by heistermann** [comment]
See Pull Request #97 for updating the release notes.

**Comment by kmuehlbauer** [comment]
OK, I think we are done here. 

@heistermann If you agree, I'll take the necessary steps to create wradlib release `0.9.0` asap.

**Comment by heistermann** [comment]
Absolutely yes. Thanks in advance!

**Comment by kmuehlbauer** [comment]
There was some glitch in .travis.yaml pointing devel and release to testpypi. So the release was uploaded to testpypi. I manually uploaded it to pypi-too. A PR which fixes this behaviour follows.
